my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import *
from room.views import *
from hotel.views import *


urlpatterns = [
    
    path('admin/', admin.site.urls),
    
    path('', home, name="home"),
    
    path('login/', login_page, name="login"),
    path('logout/', logout_user, name="logout"),
    path('register/', register_page, name="register"),

    path('guests/', guests, name="guests"),
    path('employees/', employees, name="employees"),
    path('events/', events, name="events"),
    path('bookings/', bookings, name="bookings"),
    path('rooms/', rooms, name="rooms"),
    path('room-services/', room_services, name="room-services"),
    path('announcements/', announcements, name="announcements"),
    path('refunds/', refunds, name="refunds"),
    path('storage/', storage, name="storage"),

    path('tasks/', tasks, name="tasks"),
    path('current-room-services/', current_room_services,
         name="current-room-services"),
    path('request-refund/', request_refund, name="request-refund"),
    path('event-profile/<str:id>/', event_profile, name="event-profile"),
    path('event-edit/<str:pk>/', event_edit, name="event-edit"),
    path('add-room/', add_room, name="add-room"),

    path('employee-profile/<str:pk>/', employee_details, name="employee-profile"),
    path('employee-edit/<str:pk>/', employee_details_edit, name="employee-edit"),
    path('employee-add/', add_employee, name="add-employee"),

    path('guest-edit/<str:pk>', guest_edit, name="guest-edit"),
    path('guest-profile/<str:pk>', guest_profile, name="guest-profile"),
    path('room-profile/<str:id>/', room_profile, name="room-profile"),
    path('room-edit/<str:pk>/', room_edit, name="room-edit"),
    path('error/', error, name="error"),

    path('booking-make/', booking_make, name="booking-make"),
    path('payment/', payment, name="payment"),
    path('verify/', verify, name="verify"),

    path('deleteStorage/<str:pk>/', deleteStorage, name="deleteStorage"),
    path('deleteFoodMenu/<str:pk>/', deleteFoodMenu, name="deleteFoodMenu"),
    path('food-menu/', food_menu, name="food-menu"),
    path('food-menu/<str:pk>/', food_menu_edit, name="food-menu-edit"),

    path('createEvent/', createEvent, name="createEvent"),
    path('deleteEvent/<str:pk>/', deleteEvent, name="deleteEvent"),
    path('deleteAnnouncement/<str:pk>/',
         deleteAnnouncement, name="deleteAnnouncement"),
    path('deleteBooking/<str:pk>/', deleteBooking, name="deleteBooking"),
    path('completeTask/<str:pk>/', completeTask, name="completeTask"),
]

hotel/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

from accounts.models import Guest, Employee


# Create your models here.
class Announcement(models.Model):
    content = models.TextField()
    sender = models.ForeignKey(Employee, null=True, on_delete=models.CASCADE)
    date = models.DateField(default=timezone.now)

    def __str__(self):
        return str(self.sender)


class Event(models.Model):
    EVENT_TYPES = (
        ('Movie', 'Movie'),
        ('Theater', 'Theater'),
        ('Conference', 'Conference'),
        ('Concert', 'Concert'),
        ('Entertainment', 'Entertainment'),
        ('Live Music', 'Live Music'),
    )

    eventType = models.CharField(max_length=20, choices=EVENT_TYPES)
    location = models.CharField(max_length=100)
    startDate = models.DateField()
    endDate = models.DateField()
    explanation = models.TextField()

    def __str__(self):
        return str(self.eventType)


class EventAttendees(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    numberOfDependees = models.IntegerField(default=0)
    guest = models.ForeignKey(Guest,   null=True, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.event) + " " + str(self.guest)


class Bills(models.Model):
    guest = models.ForeignKey(Guest,   null=True, on_delete=models.CASCADE)
    totalAmount = models.FloatField()
    summary = models.TextField()
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.guest) + " " + str(self.summary) + " " + str(self.totalAmount)


class FoodMenu(models.Model):
    startDate = models.DateField()
    endDate = models.DateField()
    menuItems = models.TextField()

    def __str__(self):
        return str(self.menuItems) + " " + str(self.startDate)


class Report(models.Model):
    date = models.DateField(default=timezone.now)
    content = models.TextField()

    def __str__(self):
        return str(self.content) + " " + str(self.date)


class Storage(models.Model):
    ITEM_TYPES = (
        ('Kitchen', 'kitchen'),
        ('Cleaning', 'cleaning'),
        ('Electronic', 'Electronic'),
        ('Textile ', 'textile '),
        ('Other', 'other'),
    )
    itemName = models.CharField(max_length=100)
    itemType = models.CharField(max_length=20, choices=ITEM_TYPES)
    quantitiy = models.IntegerField()

    def __str__(self):
        return str(self.itemName)

room/models.py
from django.db import models
from django.utils import timezone

from accounts.models import Guest
# Create your models here.


class Room(models.Model):
    ROOM_TYPES = (
        ('King', 'King'),
        ('Luxury', 'Luxury'),
        ('Normal', 'Normal'),
        ('Economic', 'Economic'),

    )
    number = models.IntegerField(primary_key=True)
    capacity = models.SmallIntegerField()
    numberOfBeds = models.SmallIntegerField()
    roomType = models.CharField(max_length=20, choices=ROOM_TYPES)
    price = models.FloatField()
    statusStartDate = models.DateField(null=True)
    statusEndDate = models.DateField(null=True)

    def __str__(self):
        return str(self.number)


class Booking(models.Model):
    roomNumber = models.ForeignKey(Room, on_delete=models.CASCADE)
    guest = models.ForeignKey(Guest, null=True, on_delete=models.CASCADE)
    dateOfReservation = models.DateField(default=timezone.now)
    startDate = models.DateField()
    endDate = models.DateField()

    def numOfDep(self):
        return Dependees.objects.filter(booking=self).count()

    def __str__(self):
        return str(self.roomNumber) + " " + str(self.guest)


class Dependees(models.Model):
    booking = models.ForeignKey(Booking,   null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def str(self):
        return str(self.booking) + " " + str(self.name)


class Refund(models.Model):
    guest = models.ForeignKey(Guest,   null=True, on_delete=models.CASCADE)
    reservation = models.ForeignKey(Booking, on_delete=models.CASCADE)
    reason = models.TextField()

    def __str__(self):
        return str(self.guest)


class RoomServices(models.Model):
    SERVICES_TYPES = (
        ('Food', 'Food'),
        ('Cleaning', 'Cleaning'),
        ('Technical', 'Technical'),
    )

    curBooking = models.ForeignKey(
        Booking,   null=True, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    createdDate = models.DateField(default=timezone.now)
    servicesType = models.CharField(max_length=20, choices=SERVICES_TYPES)
    price = models.FloatField()

    def str(self):
        return str(self.curBooking) + " " + str(self.room) + " " + str(self.servicesType)

room/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from .models import *


class editRoom(ModelForm):
    class Meta:
        model = Room
        fields = ["capacity", "numberOfBeds", "roomType", "price"]


class editBooking(ModelForm):
    class Meta:
        model = Booking
        fields = ["startDate", "endDate"]


class editDependees(ModelForm):
    class Meta:
        model = Dependees
        fields = ["booking", "name"]

room/views.py
# imports
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

from django.db.models import Q, Count
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.models import Group, User

from datetime import datetime, date, timedelta
import random
# Create your views here.
from accounts.models import *
from room.models import *
from hotel.models import *
from .forms import *



@ login_required(login_url='login')
def rooms(request):
    role = str(request.user.groups.all()[0])
    path = role + "/"
    rooms = Room.objects.all()
    firstDayStr = None
    lastDateStr = None

    def chech_availability(fd, ed):
        availableRooms = []
        for room in rooms:
            availList = []
            bookingList = Booking.objects.filter(roomNumber=room)
            if room.statusStartDate == None:
                for booking in bookingList:
                    if booking.startDate > ed.date() or booking.endDate < fd.date():
                        availList.append(True)
                    else:
                        availList.append(False)
                if all(availList):
                    availableRooms.append(room)
            else:
                if room.statusStartDate > ed.date() or room.statusEndDate < fd.date():
                    for booking in bookingList:
                        if booking.startDate > ed.date() or booking.endDate < fd.date():
                            availList.append(True)
                        else:
                            availList.append(False)
                        if all(availList):
                            availableRooms.append(room)

        return availableRooms

    if request.method == "POST":
        if "dateFilter" in request.POST:
            firstDayStr = request.POST.get("fd", "")
            lastDateStr = request.POST.get("ld", "")

            firstDay = datetime.strptime(firstDayStr, '%Y-%m-%d')
            lastDate = datetime.strptime(lastDateStr, '%Y-%m-%d')

            rooms = chech_availability(firstDay, lastDate)

        if "filter" in request.POST:
            if (request.POST.get("number") != ""):
                rooms = rooms.filter(
                    number__contains=request.POST.get("number"))

            if (request.POST.get("capacity") != ""):
                rooms = rooms.filter(
                    capacity__gte=request.POST.get("capacity"))

            if (request.POST.get("nob") != ""):
                rooms = rooms.filter(
                    numberOfBeds__gte=request.POST.get("nob"))

            if (request.POST.get("type") != ""):
                rooms = rooms.filter(
                    roomType__contains=request.POST.get("type"))

            if (request.POST.get("price") != ""):
                rooms = rooms.filter(
                    price__lte=request.POST.get("price"))

            context = {
                "role": role,
                "rooms": rooms,
                "number": request.POST.get("number"),
                "capacity": request.POST.get("capacity"),
                "nob": request.POST.get("nob"),
                "price": request.POST.get("price"),
                "type": request.POST.get("type")
            }
            return render(request, path + "rooms.html", context)

    context = {
        "role": role,
        'rooms': rooms,
        'fd': firstDayStr,
        'ld': lastDateStr
    }
    return render(request, path + "rooms.html", context)


@login_required(login_url='login')
def add_room(request):
    role = str(request.user.groups.all()[0])
    path = role + "/"

    if request.method == "POST":
        guest = None
        if role == 'guest':
            guest = request.user.guest
        elif role == 'manager' or role == 'admin' or role == 'receptionist':
            guest = request.user.employee

        # announcement = Announcement(sender = sender, content = request.POST.get('textid'))
        number = request.POST.get('number')
        capacity = request.POST.get('capacity')
        numberOfBeds = request.POST.get('beds')
        roomType = request.POST.get('type')
        price = request.POST.get('price')
        print(capacity)
        room = Room(number=number, capacity=capacity,
                    numberOfBeds=numberOfBeds, roomType=roomType, price=price)

        room.save()
        return redirect('rooms')

    context = {
        "role": role
    }
    return render(request, path + "add-room.html", context)


@login_required(login_url='login')
def room_profile(request, id):
    role = str(request.user.groups.all()[0])
    path = role + "/"
    tempRoom = Room.objects.get(number=id)
    bookings = Booking.objects.filter(roomNumber=tempRoom)
    guests = Guest.objects.all()
    bookings2 = Booking.objects.all()
    context = {
        "role": role,
        "bookings": bookings,
        "room": tempRoom,
        "guests": guests,
        "bookings2": bookings2
    }

    if request.method == "POST":
        if "lockRoom" in request.POST:
            fd = request.POST.get("bsd")
            ed = request.POST.get("bed")
            fd = datetime.strptime(fd, '%Y-%m-%d')
            ed = datetime.strptime(ed, '%Y-%m-%d')
            check = True
            for b in bookings:
                if b.endDate >= fd.date() and b.startDate <= ed.date():
                    check = False
                    break
            if check:
                tempRoom.statusStartDate = fd
                tempRoom.statusEndDate = ed
                tempRoom.save()
            else:
                messages.error(request, "There is a booking in the interval!")
        if "unlockRoom" in request.POST:
            tempRoom.statusStartDate = None
            tempRoom.statusEndDate = None
            tempRoom.save()
        if "deleteRoom" in request.POST:
            check = True
            for b in bookings:
                if b.startDate <= datetime.now().date() or b.endDate >= datetime.now().date():
                    check = False
            if check:
                tempRoom.delete()
                return redirect("rooms")
            else:
                messages.error(request, "There is a booking in the interval!")

    return render(request, path + "room-profile.html", context)


@login_required(login_url='login')
def room_edit(request, pk):
    role = str(request.user.groups.all()[0])
    path = role + "/"

    room = Room.objects.get(number=pk)
    form1 = editRoom(instance=room)

    context = {
        "role": role,
        "room": room,
        "form1": form1
    }

    if request.method == 'POST':
        form1 = editRoom(request.POST, instance=room)
        if form1.is_valid():
            form1.save()
            return redirect("room-profile", id=room.number)
    return render(request, path + "room-edit.html", context)


@ login_required(login_url='login')
def room_services(request):
    role = str(request.user.groups.all()[0])
    path = role + "/"

    room_services = RoomServices.objects.all()
    context = {
        "role": role,
        "room_services": room_services
    }
    return render(request, path + "room-services.html", context)


@login_required(login_url='login')
def current_room_services(request):
    import datetime

    role = str(request.user.groups.all()[0])
    path = role + "/"

    curGuest = Guest.objects.get(user=request.user)
    curBooking = Booking.objects.filter(guest=curGuest).last()
    if curBooking is not None:
        curRoom = Room.objects.get(number=curBooking.roomNumber.number)
    else:
        context = {
            "role": role,
            "error": "You Don't Have Booking Right Now"
        }
        return render(request, path + "current-room-services.html", context)
    curRoomServices = RoomServices.objects.filter(curBooking=curBooking)

    room_services = RoomServices.objects.all()

    group = Group.objects.get(name='staff')
    users = User.objects.filter(groups=group)
    allEmployees = Employee.objects.filter(user__in=users)
    availableEmployee = list()
    maxTaskNum = 10

    for e in allEmployees:
        counter = 0
        empTasks = Task.objects.filter(employee=e)
        for t in empTasks:
            counter += 1
        if counter < maxTaskNum:
            availableEmployee.append(e)

    context = {
        "role": role,
        "room_services": room_services,
        "curGuest": curGuest,
        "curBooking": curBooking,
        "curRoom": curRoom,
        "curRoomServices": curRoomServices
    }

    if request.method == "POST":
        if "foodReq" in request.POST:
            newServiceReq = RoomServices(
                curBooking=curBooking, price=50.0, room=curRoom,  servicesType='Food')
            newServiceReq.save()

            chosenEmp = random.choice(availableEmployee)
            lastTask = Task.objects.filter(employee=chosenEmp).last()
            if(lastTask != None):
                newTask = Task(employee=chosenEmp, startTime=lastTask.endTime,
                               endTime=lastTask.endTime+datetime.timedelta(minutes=30), description="Food Request")
            else:
                newTask = Task(employee=chosenEmp, startTime=datetime.datetime.now(),
                               endTime=datetime.datetime.now()+datetime.timedelta(minutes=30), description="Food Request")
            newTask.save()
            return redirect("current-room-services")

        if "cleaningReq" in request.POST:
            newServiceReq = RoomServices(
                curBooking=curBooking, price=0.0, room=curRoom,  servicesType='Cleaning')
            newServiceReq.save()
            chosenEmp = random.choice(availableEmployee)
            lastTask = Task.objects.filter(employee=chosenEmp).last()

            if(lastTask != None):
                newTask = Task(employee=chosenEmp, startTime=lastTask.endTime,

templates/common_pages/authorized-announcements.html
<div class="container py-5">


    <div class="table-header row">

        <div class="col-sm-12 col-md-12 col-lg-4 mb-4">
            <h2>Announcements List</h2>
        </div>

    </div>
    <table class="table table-hover table-striped">
        <thead class="bg-secondary rounded">
            <tr>
                <form action="" method="POST">
                    {% csrf_token %}
                    <th>ID<input type="number" name="id" value="{{id}}" class="form-control border border-secondary">
                    </th>

                    <th>Content<input type="text" name="content" value="{{content}}"
                            class="form-control border border-secondary"></th>


                    <th>Sender Name<input type="text" name="name" value="{{name}}"
                            class="form-control border border-secondary"></th>

                    <th>Announced Date<input type="date" class="form-control border border-secondary" name="date"
                            value="{{date}}"></th>
                    <th><button type="submit" name="filter" class="btn btn-warning w-100">Filter</button></th>

                </form>
            </tr>
        </thead>
        <tbody>
            {% for announcement in announcements %}
            <tr>
                <td>{{announcement.id}}</td>
                <td>{{announcement.content}}</td>
                <td>{{announcement.sender.user.first_name}} {{announcement.sender.user.last_name}}</td>
                <td>{{announcement.date}}</td>
                {% if role == "manager" or role == "admin" %}
                <td> <a href="{% url 'deleteAnnouncement' announcement.id %}"
                        class="btn btn-sm btn-danger px-3">Delete</a> </td>
                {% else %}
                <td></td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>

    </table>

</div>


{% if role == "manager" or role == "admin" %}

<div class="add-annoucment border-top my-3 mx-5 p-5">
    <h4>Add Announcement</h4>
    <form action="" method="POST">
        {% csrf_token %}

        <div class="form-group">
            <textarea class="form-control" name="textid" rows="8" placeholder="Enter Content of Announcement"
                id="textid">

            </textarea>
        </div>
        <button type="submit" class="btn btn-success btn-lg px-4 float-right" name="sendAnnouncement">Send</button>
    </form>
</div>
</div>

{% endif %}
</div>

templates/common_pages/booking-make.html
<div class="container">

    <div class="row py-5 h5">
        <p>You are currently trying to book This room:
            <br>
            Between {{fd}} - {{ld}}
            <br>
            Room Number : {{ room.number }}
            <br>
            Room capacity : {{ room.capacity }}
            <br>
            Number of beds in the room : {{ room.numberOfBeds }}
            <br>
            Room Type : {{ room.roomType }}
            <br>
            Room price : {{ room.price }}
            <br>
            <br>
            Total price : {{total}}
        </p>
    </div>


    <form action="" method="POST">
        {% csrf_token %}
        <div class=row>
            <input type="hidden" value="{{ room }}" name="roomid">
            <input type="date" value="{{ fd }}" name="fd" class="d-none">
            <input type="date" value="{{ ld }}" name="ld" class="d-none">
            {% if room.capacity > 1 %}
            <div class="col-6">
                <h4>Add Dependee</h4>
                <input type="text" class="form-control d-inline" name="depName">
                <button type="submit" name="add"
                    class="form-control btn btn-sm btn-outline-success px-3 d-inline">Add</button>
            </div>

            <div class="col-6">
                <ul id="myList" class="list-group">
                    <h4>List Of Dependees</h4>
                    {% for n in names %}
                    <li class="list-group-item">{{n}}<input type="hidden" name="name{{forloop.counter}}" value="{{n}}">
                    </li>
                    {% endfor %}
                </ul>
            </div>
            {% endif %}

            {% if role == "receptionist" %}

            <label for="exampleFormControlSelect1">Select A Guest
            </label>
            <select class="form-control" name="guest" required="" id="id_guest">
                {% for guest in guests %}
                <option value="{{guest.id}}">{{guest.user.first_name}} {{guest.user.last_name}}</option>
                {% endfor %}
            </select>
            {% endif %}

            <button type="submit" class="btn btn-info w-100 mt-3" name="bookGuestButton">Book</button>
        </div>
    </form>


    <div class="py-3">
        &nbsp
    </div>

</div>

templates/common_pages/deleteBooking.html
<div class="row justify-content-center m-5">

    <div class="card border-danger shadow-lg w-75">

        <div class="card-body">

            <p>Are you sure you want to delete This Booking : ?</p> <br>
            <p>Room number : {{ booking.roomNumber.number }} </p> <br>
            <p>Guest name : {{ booking.guest.user.first_name }} {{ booking.guest.user.last_name }}</p><br>
            <p>from {{ booking.startDate }} to {{ booking.endDate }}</p>

            <form action="{% url 'deleteBooking' booking.id %}" method="post">
                {% csrf_token %}
                <a class="btn btn-info" href="{% url 'bookings' %}">Cancel</a>

                <input class="btn btn-danger" type="submit" value="Confirm">
            </form>

        </div>

    </div>

</div>
&nbsp

templates/common_pages/event-edit.html
<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        <div class="row mt-5">
            <div class="col-6  border-right pr-5">

                <div class="form-group row">
                    <label for="item-type" class="col-sm-3 col-form-label h4">Event Type:</label>
                    <div class="col-sm-9">
                        <select name="eventType" required="" id="id_eventType" class="form-control">
                            <option value="Movie" {% if event.eventType == 'Movie' %} selected="" {% endif %}>Movie
                            </option>

                            <option value="Theater" {% if event.eventType == 'Theater' %} selected="" {% endif %}>
                                Theater
                            </option>

                            <option value="Conference" {% if event.eventType == 'Conference' %} selected="" {% endif %}>
                                Conference</option>

                            <option value="Concert" {% if event.eventType == 'Concert' %} selected="" {% endif %}>
                                Concert
                            </option>

                            <option value="Entertainment" {% if event.eventType == 'Entertainment' %} selected=""
                                {% endif %}>Entertainment</option>

                            <option value="Live Music" {% if event.eventType == 'Live Music' %} selected="" {% endif %}>
                                Live Music</option>

                        </select>
                    </div>
                </div>

                <br>

                <div class="form-group row">
                    <label for="item-type" class="col-sm-3 col-form-label h4">Start Date:</label>
                    <div class="col-sm-9">
                        <input type="date" class="form-control" id="id_startDate" name="startDate"
                            value="{{ event.startDate|date:'Y-m-d'}}">
                    </div>
                </div>

            </div>

            <div class="col-6 pl-5">

                <div class="form-group row">
                    <label for="item-type" class="col-sm-3 col-form-label h4">Location:</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="id_location" name="location"
                            value="{{event.location}}">
                    </div>
                </div>

                <br>

                <div class="form-group row">
                    <label for="item-type" class="col-sm-3 col-form-label h4">End Date:</label>
                    <div class="col-sm-9">
                        <input type="date" class="form-control" id="id_endDate" name="endDate"
                            value="{{ event.endDate|date:'Y-m-d' }}">
                    </div>
                </div>

            </div>
        </div>

        <br>

        <div class="explanation py-5 border-top border-secondary">
            <div class="header h2 border rounded p-4">Explanation</div>
            <div class="content">
                <div class="form-group">
                    <textarea class="form-control" id="id_explanation" name="explanation" rows="8">
                    {{ event.explanation }}
                    </textarea>
                </div>
            </div>
            <button type="submit" class="btn btn-success btn-lg px-5 float-right">Save</button>
        </div>

    </form>
</div>

templates/common_pages/food-menu-edit.html
<div class="container clear-fix">
    <form action="" method="POST">
        {% csrf_token %}
        <div class="row mt-5 clear-fix">
            <div class="col-6 pr-3 border-right">

                <div class="form-group pt-3">
                    <label for="menu_items"><b>Menu Items</b></label>
                    <input type="text" class="form-control border border-secondary" id="id_menu_items"
                        value="{{food_menu.menuItems}}" name="menuItems">
                </div>

                <div class="form-group pt-3">
                    <label for="start_date"><b>Start Date</b></label>
                    <input type="date" class="form-control border border-secondary" id="id_start_date" name="startDate"
                        value="{{food_menu.startDate|date:'Y-m-d'}}">
                </div>

                <div class="form-group">
                    <label for="end_date"><b>End Date</b></label>
                    <input type="date" class="form-control border border-secondary" id="id_endDate"
                        value="{{food_menu.endDate|date:'Y-m-d'}}" name="endDate">
                </div>
            </div>

        </div>
        <div class="clear-fix mb-5 pb-5">

            <button type="submit" name="submit" class="btn btn-success float-right">Save Changes</button>
        </div>
    </form>

</div>

templates/common_pages/room-edit.html
<div class="container">
    <div class="shadow-lg p-5">
        <form action="" method="POST">
            {% csrf_token %}
            <div class="row mt-5">
                <div class="col-6">

                    <div class="form-group">
                        <label for="item-quantity"><b>Number Of Beds: </b></label>
                        <input type="number" min="0" class="form-control border border-secondary"
                            value="{{room.numberOfBeds}}" id="id_numberOfBeds" name="numberOfBeds">
                    </div>

                    <div class="form-group">
                        <label for="item-quantity"><b>Price: </b></label>
                        <input type="number" min="0" step="0.01" class="form-control border border-secondary"
                            value="{{room.price}}" id="id_price" name="price">
                    </div>

                </div>

                <div class="col-6">

                    <div class="form-group ">
                        <label for="item-type"><b>Capacity : </b></label>
                        <input type="number" min="1" class="form-control border border-secondary"
                            value="{{room.capacity}}" id="id_capacity" name="capacity">
                    </div>

                    <div class="form-group">
                        <label for="item-quantity"><b>Room Type</b></label>
                        <select name="roomType" required="" id="id_roomType"
                            class="form-control border border-secondary">

                            <option value="King" {% if room.roomType == 'King' %} selected {% endif %}>King</option>

                            <option value="Luxury" {% if room.roomType == 'Luxury' %} selected {% endif %}>Luxury
                            </option>

                            <option value="Normal" {% if room.roomType == 'Normal' %} selected {% endif %}>Normal
                            </option>

                            <option value="Economic" {% if room.roomType == 'Economic' %} selected {% endif %}>Economic
                            </option>

                        </select>
                    </div>
                    <button type="submit" name="submit" class="btn btn-outline-success float-right">Save
                        Changes</button>
                </div>

            </div>
        </form>
        <br>


    </div>
</div>